### ISSUE TITLE
Klassendiagramm(e) erstellen

### ISSUE THREAD

**Issue by klaus94** [tilowerdin/Influence_Pro#1]
Das müssen wir uns überlegen:

- [x] **Wie verknüpfen wir den View mit dem Model? (Insbesondere: Wie läuft die Kommunikation zwischen DataCell und VisualCell?)**
- [x] Macht eine Cell - Factory - Klasse Sinn?
- [ ] Klassendiagramm verfeinern - also welche Methoden werden gebraucht?

**Comment by klaus94** [comment]
Auf dieser Seite sind Entwurfsmuster aufgelistet und erklärt: https://medium.com/android-news/android-architecture-2f12e1c7d4db
Da müssen wir nun überlegen, welches für unsere Zwecke am besten ist.

**Comment by klaus94** [comment]
Vorläufige Idee: eine CellFactory erzeugt zu Beginn eines Spieles Zellen. Es werden gleichzeitig ModelCells und VisualCells erstellt und über das Observer-Pattern miteinander verbunden. Dabei nimmt die VisualCel die Rolle des Beobachters ein und die ModelCell die des Subjektes. Somit kann eine ModelCell die zugehörige VisualCell benachrichtigen, wenn sich ihr Zustand ändert. Die VisualCell holt sich daraufhin die nötigen Daten (capacity, owner, ...). Wird das Spielfeld nun aktualisiert, kann direkt auf die Daten in der VisualCell zugegriffen werden.

**Comment by KoehlerTill** [comment]
Klassendiagramm verfeinert und überarbeitet. Ready to fly!

Frage: Wie realisieren wir die Verbindung der GameActivity mit der HumanPlayerEngine? Observer oder BusyWaiting?

**Comment by klaus94** [comment]
Ich würde vorschlagen, wir versuchen erst mal buisy waiting.
