### ISSUE TITLE
Attack-Klasse: zufälliges Gewinnen verbessern

### ISSUE THREAD

**Issue by klaus94** [tilowerdin/Influence_Pro#30]

**Comment by KoehlerTill** [comment]
Zufälliges Gewinnen ist nun verbessert.
Gewinnwahrscheinlichkeit in Unterzahl oder bei Gleichstand: 0,5^(-diff+1)
Gewinnwahrscheinlichkeit in Überzahl: 0,5 + 0,5^(diff+1)
... mit diff = Kapazität_Angr - Kapazität_Vert
